In [1]:
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Han Xiao <artex.xh@gmail.com> <https://hanxiao.github.io>
# https://github.com/hanxiao/bert-as-service
# NOTE: First install bert-as-service via
# $
# $ pip install bert-serving-server
# $ pip install bert-serving-client
# $

# simple similarity search on FAQ

In [2]:
import numpy as np
from bert_serving.client import BertClient
from termcolor import colored

In [3]:
#with BertClient(port=4000, port_out=4001) as bc:
bc = BertClient()

In [4]:
prefix_q = '##### **Q:** '
topk = 5

In [ ]:
with open('kor_test.txt') as fp:
	questions = [v.replace(prefix_q, '').strip() for v in fp if v.strip() and v.startswith(prefix_q)]
	print('%d questions loaded, avg. len of %d' % (len(questions), np.mean([len(d.split()) for d in questions])))

4 questions loaded, avg. len of 1


In [ ]:
#with BertClient(port=4000, port_out=4001) as bc:
with BertClient() as bc:
    doc_vecs = bc.encode(questions)

    while True:
        query = input(colored('your question: ', 'green'))
        query_vec = bc.encode([query])
        # compute normalized dot product as score
        print(query_vec.shape)
        print(query_vec[0][:5])
        #print(query_vec[0].shape)
        
        #print(query_vec[0])
        score = np.sum(query_vec * doc_vecs, axis=1) / np.linalg.norm(doc_vecs, axis=1)
        topk_idx = np.argsort(score)[::-1][:topk]
        print('top %d questions similar to "%s"' % (topk, colored(query, 'green')))
        for idx in topk_idx:
            print('> %s\t%s' % (colored('%.1f' % score[idx], 'cyan'), colored(questions[idx], 'yellow')))

your question: asdf
(1, 768)
[-0.7654451  -1.3474596   2.0928333   0.27605778  0.09556187]
top 5 questions similar to "asdf"
> 29.0	대학교 가까이
> 28.0	학교입니까
> 27.4	열마나 힘들까?
> 27.2	이거 얼마입니까?
your question: ㅁㄴㅇㄹ
(1, 768)
[-0.36139655 -0.12814492 -0.01868746  0.20281714 -0.02859865]
top 5 questions similar to "ㅁㄴㅇㄹ"
> 29.9	대학교 가까이
> 28.5	학교입니까
> 28.3	열마나 힘들까?
> 27.7	이거 얼마입니까?
your question: 가자
(1, 768)
[ 0.41116357 -0.6338894   0.86293685  0.92936254  0.04906339]
top 5 questions similar to "가자"
> 33.0	대학교 가까이
> 31.9	학교입니까
> 30.9	열마나 힘들까?
> 30.6	이거 얼마입니까?
your question: 우리
(1, 768)
[ 0.19881919 -0.6241618   0.89921445  0.06072361 -0.05975375]
top 5 questions similar to "우리"
> 32.6	대학교 가까이
> 32.3	학교입니까
> 31.7	열마나 힘들까?
> 30.8	이거 얼마입니까?
your question: 대학교
(1, 768)
[-0.04995814 -0.8282616   1.5657754   0.01366904 -0.33730385]
top 5 questions similar to "대학교"
> 32.3	대학교 가까이
> 29.8	학교입니까
> 28.7	열마나 힘들까?
> 27.8	이거 얼마입니까?
your question: 이거
(1, 768)
[ 0.43574762 -0.731406    0.4074267   0.73705906 -0.8